### ISSUE TITLE
Implement a single-lake box model for calcium in Streamlit

### ISSUE THREAD

**Issue by JamesSample** [NIVANorge/lake_liming_app#11]
The original model for lake calcium concentration used in TPKALK is briefly described [here](https://niva.brage.unit.no/niva-xmlui/bitstream/handle/11250/208709/3412_200dpi.pdf?sequence=2&isAllowed=y#page=34). 

I've created a rough Python version in the notebook [here](https://nbviewer.org/github/NIVANorge/lake_liming_app/blob/main/notebooks/box_model.ipynb).

My version needs checking and then adding to the `Lake modelling` tab of the Streamlit application. As a starting point, users should be able to enter the following information

#### Lake characteristics
 - Initial lake Ca concentration (mg/l)
 - Lake inflow Ca concentration (mg/l)
 - Lake area (km2)
 - Mean lake depth (m)
 - Mean flow rate (m3/s)

#### Liming parameters
 - Lime "dose" (mg-lime/l)
 - Lime Ca content by mass (%)
 - Lime overdosing factor (-)
 - $K_L$ (parameter controlling rate of dissolution of lake bottom lime; $month^{-1}$)

### Model setup
 - Number of months to simulate after liming

Having entered this information, users should be able to click a button to run the model and see a **plot of simulated Ca concentrations against time** (something like the plot in my notebook, but probably implemented using e.g. Altair, rather than Matplotlib). Ideally, we should also include a **plot of estimated changes in pH over time** too, but #8 needs clarifying first.

Some points to keep in mind:

 - Eventually, users will probably want to select from a list of pre-defined lime products stored in a database and have the `liming parameters` filled-in automatically. However, they still need to be able to enter custom parameters, if desired. Ideally, they should also be able to take values for these parameters from the `Column tests` tab. Furthermore, it will probably be helpful to plot results for several limes on the same axes i.e. to define the lake characteristics, then select one or more limes from the database and see the results overlaid for easy comparison. **I suggest we ignore all this initially and just enter parameters manually for a single product**, but these extensions are something to keep in mind when structuring the code.
 
 - We just need a rough solution initially, as a starting point for further discussion. The model and its outputs etc. will likely change, so no need to worry about making it beautiful at this stage.

@nmarquesin @IvanaH8 Is this something one of you might be interested in doing? Thanks!

**Comment by nmarquesin** [comment]
I copied and pasted @JamesSample calculations from his [notebook](https://nbviewer.org/github/NIVANorge/lake_liming_app/blob/main/notebooks/box_model.ipynb), adding user inputs and an Altair plot for the results.
In this first rough version the user should be able add lake parameters, choose between 2 different liming products or add custom values. The length of the simulation can also be edited.
The plot is automatically updated, so there is no button run the calculations. This can be added if necessary. 
This version is not deployed, to check locally please download the branch and `streamlit run app.py`.

**Comment by nmarquesin** [comment]
Regarding updating the app to reflect the most current model, which is not yet finalized, I think it's down your preference between using the app itself or Jupyter notebooks during model/delivery discussions. If you prefer to use the app, it makes sense to keep it as updated as possible. If that's the case, would updating it once a week/every two weeks be enough to be helpful? I can merge the current changes and start working on the new features as soon as you think it's useful.

I see some of these new features produced additional outputs, like a plot of varying lime doses for the same lime product. I don't understand this about our model: if the goal is to figure out how much of a given lime product needs to be added to a lake to reach a desired pH, then why are lime dose and liming frequency (overdosing) model inputs instead of outputs? Would it be possible to have desired min pH in x months or desired pH range to be user inputs instead?

In the same plot there's different residency times, does that mean that this part of our scope has changed? "(...) the application will by default assume wet spreading of lime by boat to a lake with residence time 0.7 years. "

**Comment by JamesSample** [comment]
Good points, @nmarquesin !

I think it does make sense to keep the app reasonably up-to-date, so that Karl-Jan and Miljødirektoratet can see what we already have and assess how it meets their needs. At the same time, I don't want us to use lots of resources implementing UI elements that won't be used, so we need to try to get the balance right. If you're happy incorporating these changes that's fine by me. That should bring us roughly up-to-date with the discussions I've had so far.

I don't think you need to allow for the facet grids etc. from my notebook at this stage, but if you could set up the app to take the following user input and then simulate Ca concentrations over time, that would be good:

#### Initial conditions
 
        C_lake0                  # Lake Ca concentration (mg/l)
        C_in0                    # Lake inflow concentration (mg/l)
        C_bott0                  # "Active" lime on the lake bottom at t=0 (mg/l)
        pH_lake0                 # Lake pH
        
#### Liming parameters
 
        lime_prod                # Name of product. Must be in the "database"
        lime_dose                # Dose as lime (not Ca) in mg/l
        lime_month               # Month in which lime is added. Must be < 'n_months'
        spr_meth                 # 'wet' or 'dry'
        K_L                      # Rate of dissolution of "active" bottom lime (month^-1)
        F_active                 # Proportion of lake-bottom lime that remains "active" (i.e. available for dissolution)

#### Lake characteristics
 
        area                     # km2
        mean_depth               # metres
        res_time                 # Volume / mean_annual_q
        flow_profile             # 'none', 'fjell' or 'kyst'

#### Model setup
 
        n_months                 # Number of months to simulate

I'll try to answer your other questions in the Discussions thread :-)
