### ISSUE TITLE
Refactor code for column tests

### ISSUE THREAD

**Issue by JamesSample** [NIVANorge/lake_liming_app#12]
My initial code for the `Column tests` page was very rough, and now that I understand the experimental setup better I think it needs refactoring completely. For example:

 - The instantaneous dissolution tests and the overdosing tests are essentially the same, but with one extra step at the end for the overdosing factors. My functions for these tests should be split up and made more reusable e.g. one function for the integration, one for the theoretical max concentration etc. These functions could then be reused for both the instantaneous dissolution and overdoing parts. This will also make it easier to add unit tests.
 
 - The code needs generalising to allow for magnesium as well as calcium. All lime products tested will contain calcium, and a few may also contain magnesium. I have added columns for Mg values to the template, but my code currently only handles calcium. The code should be generalised to check for whether Mg values are present and, if they are, calculations should be performed separately for both Ca and Mg. This will mean producing two sets of two curves (i.e. 2 x instantaneous dissolution and overdosing).

@nmarquesin @IvanaH8 Would either of you be willing to take a look at this? Perhaps one of you could try this and the other have a go at #11? Please let me know what you think :-)

Thanks!

**Comment by IvanaH8** [comment]
Hi @JamesSample,

Sure, @nmarquesin and I have just decided, that I can look into this and Nathalie into #11 and see how it goes :-)

**Comment by IvanaH8** [comment]
Think we can close this as well to clean up
