### ISSUE TITLE
Clarify empirical relationship between pH and Ca

### ISSUE THREAD

**Issue by JamesSample** [NIVANorge/lake_liming_app#8]
The TPKALK report uses an empirically derived relationship between pH and change in Ca concentration:

$$pH = pH_0 + A_{pH} log(\Delta Ca)$$

(see [here](https://nivanorge.github.io/lake_liming_app/lake-modelling.html#sec-ca-ph) for details). From a purely empirical perspective this is OK, but it is always nice to build physically plausible statistical models where possible. **The physical interpretation of this model is questionable**. Firstly, it only makes sense for $\Delta Ca \geq 1$; if the change in Ca concentration is less than this, the effect of liming is actually to *reduce* pH, which does not seem reasonable. Secondly, if $\Delta Ca = 0$, the result is undefined. In reality, if $\Delta Ca = 0$, the model should presumably predict no change in pH, but this does not work here.

What is the basis for this relationship? **Can we not achieve similar empirical predictive performance using a more physically plausible statistical model?** More generally, wouldn’t it make more sense to either regress expected *change* in pH against *change* in Ca, or simply pH against Ca (rather than pH against *change* in Ca)?

**Comment by knl88** [comment]
Interesting, something based on henderson-hasselbalch equation?  With equilibriums between other metals  and oxides built into it and also the bicarbonate equilibrium.

**Comment by JamesSample** [comment]
Nice - thanks Kim! That looks very helpful.

I'll take a closer look next week :-)

**Comment by JamesSample** [comment]
We have decided to use empirical data compiled by Atle Hindar instead of the original TPKALK approach.
