### ISSUE TITLE
What is the interpretation of "overdosing factors"?

### ISSUE THREAD

**Issue by JamesSample** [NIVANorge/lake_liming_app#9]
This feels like a bit of a silly question, because overdosing factors are very widely used in the liming community. However, at present **I don't understand why they are useful as a concept**, so I'm obviously missing something.

I *do* understand the chemical principles underpinning overdosing i.e. I can see why smaller proportions of the available Ca dissolve at higher doses, and why this effect needs to be accounted for somehow. Using overdosing factors seem like a strange way to do this, however. 

As an example:

> Consider adding a dose of 50 mg/l of Miljøkalk EY3 to a lake with initial pH 4.6. We want to estimate what proportion of the lime will dissolve.

### Option 1: Use the column test data directly

We have results from an experiment where 50 mg/l of Miljøkalk EY3 were added were added to a water column with pH 4.6. **After 16 hours, 23 % of the lime had dissolved**. Based on this, 23 % also seems like a reasonable estimate for the proportion of the lime that will dissolve quickly in the lake.

### Option 2: Use overdosing factors

For this approach, we first calculate the overdosing factor, $OD$, as the ratio

$$OD = \frac{D_{10}}{D_{50}}$$

where $D_{x}$ is the instantaneous dissolution for a column with dose $x$ mg/l. The proportion that dissolves is then estimated as $\frac{1}{OD}$. For Miljøkalk EY3, this corresponds to and overdosing factor of 2.2 and **the proportion that dissolves is 45 %** i.e. significantly higher than above.

**Option 1 seems to be a direct measurement of the quantity we're interested in, so why use option 2?**

**Comment by IvanaH8** [comment]
Interesting observation, I also found the factor a bit confusing the first time I was going through some docs and now I'm intrigued even more :-) 

The use of overdosing factors must be somehow justified (at least in publications I would presume so) but it might be associated with just certain conditions, and not as the best approach in others. I would argue for keeping things as simple and transparent as possible here, so I think the need/correctness of applying overdosing factors might be worth investigating.

I can try to find out

**Comment by JamesSample** [comment]
The correct interpretation of OD factors is that the percentage dissolution at dose $x$ is estimated as

$$D_x = \frac{D_{10}}{OD}$$

The fraction $\frac{1}{OD}$ is a mistake in one of the spreadsheets originally provided by MDir.

The model code [here](https://github.com/NIVANorge/lake_liming_app/blob/89b31e117d209200648f166c829878e2ddb57abe/src/lake_modelling/utils/lake_model.py#L266) performs the correct calculation.
